"use client";

import { useState } from "react";
import type { AttendancePayload, AttendanceStatus } from "@/lib/attendance";
import type { Student } from "@/lib/students";

export function AttendanceForm({ students, onSubmit, initialValue }: { students: Student[]; onSubmit: (payload: AttendancePayload) => Promise<void>; initialValue?: AttendancePayload }) {
  const [form, setForm] = useState<AttendancePayload>(initialValue || { tenantId: "default", studentId: students[0]?.id || 0, attendanceDate: new Date().toISOString().slice(0, 10), status: "PRESENT", performanceScore: undefined, remarks: "" });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  function update(field: keyof AttendancePayload, value: string | number | undefined) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { await onSubmit(form); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : "Unable to save attendance."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="space-y-6"><section className="rounded-xl border border-[#2a2a2a] bg-[#111111] p-6"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#ff6b6b]">Daily register</p><h2 className="mt-1 text-lg font-semibold text-white">Mark attendance</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium text-[#e5e5e5]">Student<select required value={form.studentId} onChange={(event) => update("studentId", Number(event.target.value))} className="mt-2 w-full rounded-lg border border-[#2a2a2a] bg-[#161616] px-3 py-2.5 text-sm outline-none focus:border-[#ff1a1a]"><option value={0} disabled>Select a student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.firstName} {student.lastName}</option>)}</select></label><Field label="Date" type="date" value={form.attendanceDate} onChange={(value) => update("attendanceDate", value)} /><label className="block text-sm font-medium text-[#e5e5e5]">Status<select value={form.status} onChange={(event) => update("status", event.target.value as AttendanceStatus)} className="mt-2 w-full rounded-lg border border-[#2a2a2a] bg-[#161616] px-3 py-2.5 text-sm outline-none focus:border-[#ff1a1a]"><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="LATE">Late</option></select></label><label className="block text-sm font-medium text-[#e5e5e5]">Performance score<input required type="number" min="0" max="10" step="1" value={form.performanceScore ?? ""} onChange={(event) => update("performanceScore", event.target.value === "" ? undefined : Number(event.target.value))} className="mt-2 w-full rounded-lg border border-[#2a2a2a] bg-[#161616] px-3 py-2.5 text-sm outline-none focus:border-[#ff1a1a]" /></label><Field label="Remarks" value={form.remarks || ""} onChange={(value) => update("remarks", value)} /></div></section>{error && <p className="rounded-lg bg-[#ef4444]/10 px-4 py-3 text-sm text-[#ff9999]">{error}</p>}<div className="flex justify-end"><button type="submit" disabled={saving || !students.length} className="rounded-lg bg-[#ff1a1a] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#2c3d46] disabled:cursor-not-allowed disabled:opacity-60">{saving ? "Saving..." : "Save attendance"}</button></div></form>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="block text-sm font-medium text-[#e5e5e5]">{label}<input required={type === "date"} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-[#2a2a2a] bg-[#161616] px-3 py-2.5 text-sm outline-none focus:border-[#ff1a1a]" /></label>; }